import { Toaster } from '@/components/ui/toaster'
import './globals.css'
import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Auth Next14',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
    

  return (
  <SessionProvider>
    <html lang="en">
      <body className={inter.className}>
        <Toaster/>
        {children}
      </body>
      </html>
  </SessionProvider>
  )
}
